// 회원가입
###
POST http://127.0.0.1:5000/user/signup
Content-Type: application/json

{
  "email": "hanghae1@naver.com",
  "nickname": "항해1",
  "blogId": "Jason",
  "password" : "12345678",
  "confirmPassword": "12345678"
}

// 로그인
###
POST http://127.0.0.1:5000/user/login
Content-Type: application/json

{
  "email": "hanghae1@naver.com",
  "password" : "12345678"
}

// 이메일, 닉네임 중복 체크
### 
POST http://127.0.0.1:5000/user/idcheck
Content-Type: application/json

{
  "nickname" : "항해99!"
}

// 예약 신청
### 
POST http://127.0.0.1:5000/api/booking/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NzY5MDQ0MiwiZXhwIjoxNjU3NzAxMjQyfQ.4sBSvY_aNurCcK-hawrIxcdHKgS4jknPCV7X0AsuP7U
Content-Type: application/json

{
  "leaf" : 1,
  "guestId": "1",
  "date": "Thu Jul 13 2022 21:00 GMT+09:00-Thu Jul 13 2022 22:00 GMT+09:00"
}

// 예약 조회
### 
GET  http://127.0.0.1:5000/api/booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NzY5MDQ0MiwiZXhwIjoxNjU3NzAxMjQyfQ.4sBSvY_aNurCcK-hawrIxcdHKgS4jknPCV7X0AsuP7U
Content-Type: application/json


// 리뷰 작성
### 
POST   http://127.0.0.1:5000/api/review/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1ODU3NDAxNSwiZXhwIjoxNjU4NTg0ODE1fQ.97_ZNHLeER5uZJ6WvkjXBfgRBQZJKjNF38I_6-P4yLs
Content-Type: application/json

{
  "review" : "좋아요",
  "rate": 6
}

// 리뷰 조회
### 
GET    http://127.0.0.1:8000/api/review/abc12345
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1ODIwNjQ4MCwiZXhwIjoxNjU4MjE3MjgwfQ.Wjv5AEipjs6151tfRmRk9Zpqw70w6GoBLYPveCrcIYM
Content-Type: application/json

// 리뷰 수정
### 
PUT   http://127.0.0.1:8000/api/review/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1ODQ3OTMxMCwiZXhwIjoxNjU4NDkwMTEwfQ.oIc_VivrHxbXLu-Y54wS1hzm7DQ1vYDhnqhswq3WaEw
Content-Type: application/json

{
  "review" : "좋지 않아요",
  "rate": 6
}

// 리뷰 삭제
### 
DELETE    http://127.0.0.1:8000/api/review/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1ODQ3OTMxMCwiZXhwIjoxNjU4NDkwMTEwfQ.oIc_VivrHxbXLu-Y54wS1hzm7DQ1vYDhnqhswq3WaEw
Content-Type: application/json
